name: Run oldest pytest tests

on:
  workflow_call:
    inputs:
      python-versions:
        description: 'Supported python versions'
        default: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
        required: false
        type: string
      mongo:
        description: 'MongoDB version'
        required: true
        type: number
      os:
        description: 'Operating system to run tests on'
        default: 'ubuntu-latest'
        required: false
        type: string
    secrets:
      codecov_token:
        description: 'Codecov token'
        required: false

jobs:
  tests:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
    env:
      OS: ${{ inputs.os }}
      PYTHON: ${{ matrix.python-version }}
      MONGODB: ${{ inputs.mongo }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MongoDB
      uses: ankane/setup-mongodb@v1
      with:
        mongodb-version: ${{ inputs.mongo }}
    - name: Set up Pipenv on python ${{ matrix.python-version }}
      uses: fizyk/actions-reuse/.github/actions/pipenv-setup@v4.4.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: false
        allow-prereleases: true
        editable: true
    - name: Install oldest supported versions
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.0
      with:
        command: pip install -r oldest/requirements.txt
    - name: Run tests without xdist
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.0
      with:
        command: pytest -c pyproject.oldest.toml -p no:xdist --cov-report=xml
    - name: Run xdist test
      uses: fizyk/actions-reuse/.github/actions/pipenv-run@v4.4.0
      with:
        command: pytest -n auto --dist loadgroup -c pyproject.oldest.toml --max-worker-restart=0 --cov-report=xml:coverage-xdist.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5.5.2
      with:
        token: ${{ secrets.codecov_token }}
        flags: linux
        env_vars: OS, PYTHON, MONGODB
        fail_ci_if_error: false
